[package]
name = "goshooter_client"
version = "1.0.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = { path = "../common" }
crossterm = "0.20.0"
crossbeam = "0.8.1"